### ISSUE TITLE
Provide year group mappings instead of codes

### ISSUE THREAD

**Issue by StevenMayocchi** [TheAlphaSchoolSystemPTYLTD/library-integration#16]
A mutual customer have asked us why their TASS Year Groups for K and P (display values) are coming across as -1 and 0 (underlying codes).

We could remap the codes to the display values if they’re hardcoded but based on a screenshot another customer sent us (Reference Year Group), it seems the display values are customisable?

Is it possible for the API to send through the display values rather than the underlying codes (or if this change isn’t possible, the display values as well as the codes), as this is what customers are expecting to see in integrating products?

**Comment by ricardorusson** [comment]
This has been resolved in #17 38a53c37f280a10ab2a77a1bf8d95bc02a72bc9d
